version: "3"

services:
  postgrest:
    image: postgrest/postgrest
    container_name: bp-postgrest
    ports:
      - "5112:3000"
    environment:
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres

  postgresql:
    image: postgres
    container_name: bp-psql
    ports:
      - "5111:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
